### ISSUE TITLE
Get address UTXO's

### ISSUE THREAD

**Issue by andredevjs** [deezy-inc/nosft-core#8]
#  Get address UTXO's

Creates base foundation of functionality in nosft-core to expose the getUtxo's method from [nosft](https://github.com/dannydeezy/nosft/blob/main/src/utils/utxos.js)  

---

### What problem are you trying to solve?
* _Expose core functionality to get any address utxo's in such a way in which either nosft or any other client is able to consume that functionality.._

### Why should we solve it?
* _Because nosft should be just a client of this library, we would like to have other clients to build their own projects, and this library will help them to do it._  
* _As the repo suggest, nosft core functionality should live here_

### How do you propose to solve it?
* _By exposing the method in the library in the following way:_
```js
const { nosft } = require('nosft-core');

(async () => {
    const utxos = await nosft.getAddressUtxos({ address });
    console.log(JSON.stringify(utxos, undefined, 4));
})();
```

### What other approaches did you consider?
* _We thought first to have this code in nosft, and expose an API that this library will consume, but we figure it out that some of the calls are slow, we are just going to allow this library to have the entire logic.._

### What could go wrong?
* _One of the negatives of this, is that, in order to release a new change, we will have to publish a new version of nosft-core (which get published automatically) and to update the client(s) with the new version_

**Comment by habibitcoin** [comment]
ACK, this sounds like a good idea to me!

**Comment by topether21** [comment]
It is a great idea.

**Comment by andredevjs** [comment]
Done
